jogos=["Valorant", "Terraria", "Cyberpunk 2077", "Diablo 3", "To the Moon"]
print(jogos)
jogos.append("Red Dead Redemption 2")
jogos.append("World of Warcraft")
jogos.append("Diablo 2")
print(jogos)
jogos.remove("Valorant")
jogos.remove("Cyberpunk 2077")
jogos.remove("Terraria")
jogos.remove("Diablo 3")
print(jogos)
jogos.append("The Witcher 3: Wild Hunt")
print(jogos)
jogos.pop()
print(jogos)
jogos.append("Valorant")
print(jogos)
jogos.sort()
print(jogos)
